from . import help
from . import start
from . import admin
from . import prayertime
from . import prayer_wrong_adress
from . import rus_prayer
from . import hadis
from . import bot_info
from . import quron
